### ISSUE TITLE
Clarify update arguments

### ISSUE THREAD

**Issue by rtjohn** [airbnb/knowledge-repo#248]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Can you update the documentation to clarify the nature of the arguments to add with the --update flag?
```
$ knowledge_repo --repo . add --update GitHubConnection.Rmd ./Instructions/Github.kp/orig_src/
```
Results in:
```
INFO:knowledge_repo.repositories.gitrepository:Fetching updates to the knowledge repository...
usage: knowledge_repo [--repo REPO] [--knowledge-branch KNOWLEDGE_BRANCH]
                      [--dev] [--debug] [--noupdate] [--version] [-h]
                      {init,create,drafts,status,add,submit,push,preview,runserver,deploy,db_upgrade,reindex}
                      ...
knowledge_repo: error: unrecognized arguments: ./Instructions/Github.kp/orig_src/
```

I'm trying to update the file 
```
./Instructions/Github.kp/orig_src/GitHubConnection.Rmd
```

I've already edited the file in place and now I want to add and submit the update.  I tried numerous versions of the second argument but continue to get the same error.

Even if the answer is a simple one, which I suspect it is, a bit more documentation round the --update flag would be great.

**Comment by matthewwardrop** [comment]
Hi @rtjohn!

To get help about the `add` method, you can use:
`knowledge_repo --repo <repo> add --help`

In your case, the correct command should be:
`knowledge_repo --repo <repo> add GitHubConnection.Rmd -p Instructions/Github`

Note that it is a bad idea to actually do your editing of documents within the git repository, since the `knowledge_repo` command manipulates git branches pretty frequently and you're likely to lose work eventually. It's a better idea to work on your Rmd/other source files outside of the repository (in your Documents folder say), and then add them to the repository using the appropriate `knowledge_repo` commands.

I agree that it is not super-clear how all of this works, and so in the future we'll be revamping this CLI interface, which should resolve a lot of these confusions.

I'll close this issue for now, but if issues persist, let me know!

**Comment by rtjohn** [comment]
Just to clarify for other who might read this:

```
knowledge_repo --repo . add --update ./Instructions/Github.kp/orig_src/GitHubConnection.Rmd -p Instructions/Github
```

is what worked.  Matthew did not include the --update flag in his instructions (probably an oversight) above which is what I was asking for clarification on.
