### ISSUE TITLE
Change HTML

### ISSUE THREAD

**Issue by Joaquimdcp** [airbnb/knowledge-repo#258]
Hi!

How I Can change HTML of knowledge-repo?

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by matthewwardrop** [comment]
Hi @Joaquimdcp ,

Thanks for your questions!

At this stage we have not added support for site-specific customisation of HTML/CSS. This is for two reasons:
- the html is far from complete, and hence every release is liable to break any custom html/css overrides.
- we have been working on "bigger" things.

If this is really important to you and/or others, we can bump this to a higher priority. This issue is currently tracked in #182, so closing this issue.
