### ISSUE TITLE
Automatically Update the servers once something is pushed to the knowledge repo

### ISSUE THREAD

**Issue by shashj199** [airbnb/knowledge-repo#274]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

From the documentation, I understand that it can be done but what specifically it does is not clear.

If I checkout knowledge repo in ```.resources``` folder as a git submodule then anything which is committed and pushed into the repo will get automatically updated on the servers. Does that mean that if I have a repo hosted on an EC2 machine and I update the repo on my laptop, the EC2 machine will show the updated knowledge repo? I don't have to stop the server, pull the branch manually and again deploy the webapp? Please let me know if I have a correct understanding of this concept, if not then what it is?

Also I have a confusion regarding how to setup this ```.resources``` folder, any help on this will be deeply appreciated.

Thanks a lot, it is really a cool tool.

**Comment by matthewwardrop** [comment]
Hi @shashj199 ,

The embedded .resources repository is actually focussed on making sure both client and server side code is running the same version of the knowledge repository given that they are using the same revision of the git repository, and nothing at all to do with actually syncing the git repository. At the moment, git syncing must be done manually via `git pull` or via cron or some such. We'll improve this in the future.

The .resources folder is basically a git submodule that points to this repository on some branch, so that the clients and server side code detects this embedded tooling and uses it instead of the locally installed version.

Does that make sense?

I'll close this for now, since I think the issues (like syncing) are addressed already in other issues.

Feel free to reply to this if you need more clarification :).
