### ISSUE TITLE
reindexing for updated posts?

### ISSUE THREAD

**Issue by bmabey** [airbnb/knowledge-repo#275]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Our running instance does not appear to be reindexing when the git repo is updated. (So far I have only been pushing changes to an existing post.) Do I need to explicitly turn on reindexing or what needs to be done so posts will update automatically?

**Comment by matthewwardrop** [comment]
Hi @bmabey ,

Can you describe you set up a little more?

In particular, the knowledge repo does not automatically run `git pull` on the repository (such functionality will eventually be added). If you have done that manually or via cron or some such, then the knowledge repo should automatically reindex the repository if it hasn't already done so in the last 5 minutes. It skips posts that have not had their version incremented (which is done by the standard `knowledge_repo ... add ...` command. If you're doing all of that, then let's chat some more since it should work :).

**Comment by bmabey** [comment]
Ah, okay, I thought a "reindex" involved doing a  `git pull`. I'll add a cron job to do a git pull. Thanks!

**Comment by bmabey** [comment]
BTW, we ended up using adding a webhook route via the `prepare_app` function. That may be a good way to add the functionality to the actual project.
