### ISSUE TITLE
Ascii breaks knowledge repo in title

### ISSUE THREAD

**Issue by IreneRoma** [airbnb/knowledge-repo#296]
Hi, I am using knowledge-repo in my company and we have detected an issue. 

When we put accents in a title (example: "Descripció") it doesn't work.

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

**Comment by Joaquimdcp** [comment]
+1 Here! @IreneRoma

**Comment by matthewwardrop** [comment]
@IreneRoma @Joaquimdcp Thanks for reporting this.

This is actually now fixed in #293 . Using Python 3 should fix the problem for now... but I'm expecting we'll be able to merge this into master today to solve the issue for Python 2.

Feel free to reopen if this remains an issue in Python 3, or when running off the branch of #293.
