### ISSUE TITLE
example live knowledge-repo?

### ISSUE THREAD

**Issue by gngdb** [airbnb/knowledge-repo#321]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Given that a knowledge repo can be hosted on GitHub, are there any public ones running? It would really help to get an idea of what a live one looks like, and it would be nice to clone it to look at it on a local webserver.

**Comment by matthewwardrop** [comment]
Hi @gngdb ,

We don't have any public example knowledge repositories, but you can see one yourself by running: `./run_tests.sh && ./scripts/knowledge_repo --repo tests/test_repo runserver` . If the resulting server is unstable, use `deploy` instead of `runserver`. In both cases you can access the server at http://127.0.0.1:7000 .

Best,
M
