### ISSUE TITLE
Duplication of running computationally heavy code on every commit

### ISSUE THREAD

**Issue by shashj199** [airbnb/knowledge-repo#361]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

Hey,

One of the very cool features of knowledge repo is that it checks each piece of code on every commit and shows the original output. But this feature sometimes slows things down. If a computationally heavy code is run every time, then it results in a lot of time being wasted in committing. Can we tag a code with time used for committing and skip it if nothing has changed? Just my thoughts, it might result in a lot of time-saving.

Thanks

Let me know your thoughts about it.

**Comment by matthewwardrop** [comment]
Hi @shashj199 ,

I presume you are talking the knowledge repo in the context of Rmd files here? If so, the issue here is that I'm not sure that R supports saving output of code cells between runs in a way that can be shared between all formats (including markdown, the format we use). If you know of a way to make it work, we'd love to add this feature. [In the Jupyter notebook world, cell output is saved into the document itself, and so we don't need to rerun an "knitting" process].

**Comment by shashj199** [comment]
@matthewwardrop  For now, I am using Jupyter notebooks with R kernel for any R operations, it has greatly reduced out commit time. Thanks for telling me the reason for commit time being long. you can close this.
