### ISSUE TITLE
Is knowledge-repo supported on Windows?

### ISSUE THREAD

**Issue by AlexPetit12** [airbnb/knowledge-repo#451]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

According to #133, some people are able to run knowledge-repo on Windows.

When I run 

`knowledge_repo --repo . runserver`

I get the following message

`WARNING:root:Gunicorn deployer is not available. It only works on POSIX platforms (e.g. Linux, Mac OS 
 X, etc. If you are using a POSIX platform, please ensure that `gunicorn` is installed.`

which makes me wonder how do people in #133 get knowledge-repo to work on Windows?

**Comment by timkpaine** [comment]
This is just saying you can't use gunicorn. You can use flask's built in deployer, try changing it in your config.

**Comment by matthewwardrop** [comment]
@AlexPetit12 As @timkpaine noted (thanks!), Windows is definitely supported, just not atop the default server engine of gunicorn. WSGI should work (`--engine=wsgi`). Just in case you were not aware, the `runserver` action is designed for those wanting to host a server for others to access. `run` can be used for local testing / etc.

**Comment by AlexPetit12** [comment]
@timkpaine @matthewwardrop thanks to both of you for the quick reply.

Unfortunately when I run

`knowledge_repo run --repo . --engine=wsgi`

I get

`knowledge_repo: error: invalid choice: 'run' (choose from 'init', 'create', 'drafts', 'status', 'add', 'submit', 'push', 'preview', 'runserver', 'deploy', 'db_upgrade', 'db_downgrade', 'reindex')`

as I want to run it locally. What might be the cause of this?

**Comment by matthewwardrop** [comment]
@AlexPetit12 Whoops! It's been a while since I did much work around the Knowledge Repo, and you should disregard my previous comment. I've obviously forgotten how I set things up :/.

`runserver` is the local debug server action, and `deploy` is the server deployment action. The default server engine should be `flask` for `runserver` and `preview` actions, and what is being shown here is just a warning. The server *should* actually be working just fine. To avoid this confusion in the future, I'll make that warning show only if `gunicorn` is actually selected as the deployment engine.

Have you checked to see whether the server is actually running on port 7000?

**Comment by matthewwardrop** [comment]
@AlexPetit12 Whoops! It's been a while since I did much work around the Knowledge Repo, and you should disregard my previous comment. I've obviously forgotten how I set things up :/.

`runserver` is the local debug server action, and `deploy` is the server deployment action. The default server engine should be `flask` for `runserver` and `preview` actions, and what is being shown here is just a warning. The server *should* actually be working just fine. To avoid this confusion in the future, I'll make that warning show only if `gunicorn` is actually selected as the deployment engine.

Have you checked to see whether the server is actually running on port 7000?

**Comment by matthewwardrop** [comment]
Closing this out. Feel free to reopen if you are still running into issues!
