### ISSUE TITLE
init does not create a git repository

### ISSUE THREAD

**Issue by precabal** [airbnb/knowledge-repo#482]
Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

When running the following command:
`knowledge_repo --repo <repo_path> init`

the output is:

```
-.knowledge_repo_config.yml
- README.md
```

but the documentation mentions that an empty git repo is supposed to be created if the folder does not exist.

**Comment by precabal** [comment]
I just tested this with 0.8.0 and the problem does not exist there, so it might be a bug incorporated in some of the later revisions...

**Comment by f8upd8** [comment]
Manually creating git repository just breaks everything. After i initialized the git repo inside the knowledge repo, any knowledge command such as add failed to execute. I had to manually delete the .git folder in order to restore functionality. There is no way to create a working knowledge repository in the version.
