### ISSUE TITLE
A few questions around knowledge repo

### ISSUE THREAD

**Issue by feng-tao** [airbnb/knowledge-repo#550]
1. Is the project still actively maintained by Airbnb?
2. Where does knowledge store the metadata for the posts? Are they stored in some tables?
I am looking into if it is feasible to integrate knowledge repo with our data discovery tool.

Thanks.

**Comment by bulam** [comment]
Hi Feng, 
1. Yes, I'm one of the maintainers along with a few others. I'm personally planning to work on some new features along with a UI refresh https://github.com/airbnb/knowledge-repo/blob/b4c534526bdda98e8ac6d32478e2a05a2aeadd88/README.md
2. There's two options: You can either use git as your database or you can use a MySQL as your database (recommended because it also allows posts to be submitted through the web app UI). With either option, you could connect your data discovery platform to the respective db.

Internally at Airbnb, we have a data discovery tool call the [Dataportal](https://medium.com/airbnb-engineering/democratizing-data-at-airbnb-852d76c51770) which indexes Knowledge Repo posts along with other data sources. I don't think it should be too complicated to replicate this on your end.

**Comment by feng-tao** [comment]
thanks @bulam  for the quick response! One more followup questions, if our company has already had a git repo which stores jupyter notebooks, could I reconfigure it as backend for knowledge repo? Or the git repo as data source assumes certain format in this case? Thanks.

**Comment by bulam** [comment]
@feng-tao Yes, basically, but you would need to follow two steps:

To upgrade you regular git repository to a knowledge repository, you would need to do:
- Run `knowledge_repo init` inside the git repo which would create knowledge repo config. More documentation on this [here](https://knowledge-repo.readthedocs.io/en/latest/deployment.html#git-knowledge-repositories)

Then for each Jupyter notebook:
- Add the necessary headers containing information like author, post title etc
- And then run the `knowledge repo add & knowledge_repo submit` commands for each post. More on these steps [here](https://knowledge-repo.readthedocs.io/en/latest/quickstart.html)
    - The `knowledge repo` add step converts the jupyter notebook into a knowledge repo compatible regular markdown file and creates the post metadata
