### ISSUE TITLE
pip install command throws error

### ISSUE THREAD

**Issue by ametersky** [airbnb/knowledge-repo#70]
Running `pip install git+ssh://git@github.com/airbnb/knowledge-repo.git[all]` gives the following error

```
Collecting git+ssh://git@github.com/airbnb/knowledge-repo.git[all]
  Cloning ssh://git@github.com/airbnb/knowledge-repo.git[all] to /var/folders/l4/2hk3q0sj5xx3j19r0ktrf23r0000gn/T/pip-xewbmm-build
fatal: remote error:
  %s is not a valid repository name
  Email support@github.com for help
Command "git clone -q ssh://git@github.com/airbnb/knowledge-repo.git[all] /var/folders/l4/2hk3q0sj5xx3j19r0ktrf23r0000gn/T/pip-xewbmm-build" failed with error code 128 in None
```

**Comment by matthewwardrop** [comment]
Hi @ametersky,

Thanks for your interest in the knowledge repository!

In some shells, you need to encapsulate the package name in quotes, i.e.:
`pip install "git+ssh://git@github.com/airbnb/knowledge-repo.git[all]"`

This install command is a bit outdated though, since we haven't updated our README.md properly to reflect the simplest way to install this software. The above command will install directly off the master branch, which we do not recommend. You're better off using `pip install --upgrade knowledge-repo`, which installs the latest stable release from PyPI. If you are running this on a server, it's probably worth installing all potential dependencies at the same time using `pip install --upgrade "knowledge-repo[all]"`.

Please feel free to reopen this issue if this doesn't solve your problem.

Best,
M

**Comment by ametersky** [comment]
This worked.  Thanks for the quick response -- we are excited to start using this at BuzzFeed!

**Comment by matthewwardrop** [comment]
Hoorah!

**Comment by kabadbruzzo** [comment]
Hello! I was having the same issue when I tried
`pip install git+git://github.com/mwaskom/seaborn/tree/v0.7.git`

I was getting:
```
fatal: remote error:
    mwaskom/seaborn/tree/v0.7 is not a valid repository name
```

nothing changes when I add quotation marks, but by changing the domain from git to https, the error changed to:

`fatal: repository 'https://github.com/mwaskom/seaborn/tree/v0.7/' not found`

any ideas of what is going on or what I could try next? :-(

**Comment by bulam** [comment]
hi @kabadbruzzo Is there a reason you're trying to install from git instead of just doing `pip install --upgrade knowledge-repo`?

**Comment by kabadbruzzo** [comment]
@bulam I'm not sure what your command would have done, I worked around it by downloading a .zip file from github and then doing `pip install seaborn_v0.7.zip` .
